version: "2.2.3"
services:
  server:
    image: gol/server
    container_name: gol_server_1
    build: ./server
    env_file: ./server/.env
    networks:
      - global-frontend-network
  frontend:
    image: gol/frontend
    container_name: gol_frontend_1
    build: ./frontend
    networks:
      - global-frontend-network

networks:
  global-frontend-network:
    name: ee-global-frontend-network
