// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Collections: typeof import('./components/Collections.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    EosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GOLBoard: typeof import('./components/GOLBoard.vue')['default']
    GOLCell: typeof import('./components/GOLCell.vue')['default']
    GOLInfo: typeof import('./components/GOLInfo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IcBaselineOpenInNew: typeof import('~icons/ic/baseline-open-in-new')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
