name: Test

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  build-server:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependency
        run: npm ci

  build-frontend:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependency
        run: npm ci

      - name: Build static pages
        run: npm run build

  build-contract:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: contract

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependency
        run: npm ci

      - name: Test contract
        run: npx hardhat test
