name: Test

on:
  push:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependency
        run: npm ci

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependency
        run: pnpm install

      - name: Build static pages
        run: pnpm run build

  build-contract:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependency
        run: npm ci

      - name: Test contract
        run: npx hardhat test

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-contract
      - build-frontend
      - build-server

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          scripts: cd ${{ secrets.PATH }} && docker compose up --build -d
